### PR TITLE
Fix kernel download issues

### LINKED ISSUE #5: Fix runtimejs-kernels permission error
https://github.com/runtimejs/helloworld/issues/1

```
$ runtime-qemu ./initrd
shell.js: internal error
Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/runtime-tools/runtimejs-kernels'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:799:18)
    at /usr/local/lib/node_modules/runtime-tools/node_modules/shelljs/src/mkdir.js:65:10
    at Array.forEach (native)
    at Object._mkdir (/usr/local/lib/node_modules/runtime-tools/node_modules/shelljs/src/mkdir.js:48:8)
    at Object.mkdir (/usr/local/lib/node_modules/runtime-tools/node_modules/shelljs/src/common.js:186:23)
    at module.exports (/usr/local/lib/node_modules/runtime-tools/get-prebuilt.js:8:11)
    at module.exports (/usr/local/lib/node_modules/runtime-tools/get-runtime.js:5:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/runtime-tools/bin/runtime-qemu.js:63:1)
    at Module._compile (module.js:434:26)
```

### PR DESCRIPTION
**Pull request by facekapow**
This PR fixes the kernel download issues (well, throws an informative error) when the module is installed globally and isn't run as root (but only when downloading). Fixes #5.

### CODE REVIEW

**Comment by iefserge** [comment]
@ArielAbreu that's great! the only thing I think it feels a bit weird asking user for the root access just to download the file. Maybe we can simply fallback to the home directory like `~/.runtime`?

**Comment by facekapow** [comment]
How about using `.runtime` always? That way, you don't have to download it again for different projects.

**Comment by iefserge** [comment]
@ArielAbreu sounds like a good idea :+1: 
maybe keep an optional local install as well? I guess it might be useful in some cases.

**Comment by facekapow** [comment]
Added a `--local` option to save the kernel in the module's folder.

**Comment by iefserge** [comment]
nice! one more thing to add https://github.com/runtimejs/runtime-tools/blob/fix-kernel-download/bin/runtime-qemu.js#L4 (so --local parsed as boolean)

**Comment by facekapow** [comment]
Right, thanks!

**Comment by facekapow** [comment]
OK to merge?

**Comment by iefserge** [comment]
@ArielAbreu yeah, this is great! appreciate you fixing this!
this is going to be a major version because of new location for downloads

**Pull request merged**
